# Generated by Django 4.0.5 on 2022-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('unit_price', models.FloatField(max_length=10000)),
            ],
        ),
    ]
